"""empty message

Revision ID: 20da05b98991
Revises: 9d2390b2dec4
Create Date: 2020-04-28 18:21:22.957949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20da05b98991'
down_revision = '9d2390b2dec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('firstN', sa.VARCHAR(length=64), nullable=True))
    op.add_column('connection', sa.Column('lastN', sa.VARCHAR(length=64), nullable=True))
    op.drop_index('name', table_name='connection')
    op.create_unique_constraint(None, 'connection', ['lastN'])
    op.create_unique_constraint(None, 'connection', ['firstN'])
    op.drop_column('connection', 'name')
    op.add_column('connections', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.drop_constraint('connections_ibfk_2', 'connections', type_='foreignkey')
    op.create_foreign_key(None, 'connections', 'connection', ['connection_id'], ['id'])
    op.drop_column('connections', 'student_id')
    op.alter_column('participants', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('participants', 'organizer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'organizer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('participants', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('connections', sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'connections', type_='foreignkey')
    op.create_foreign_key('connections_ibfk_2', 'connections', 'students', ['student_id'], ['id'])
    op.drop_column('connections', 'connection_id')
    op.add_column('connection', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'connection', type_='unique')
    op.drop_constraint(None, 'connection', type_='unique')
    op.create_index('name', 'connection', ['name'], unique=True)
    op.drop_column('connection', 'lastN')
    op.drop_column('connection', 'firstN')
    # ### end Alembic commands ###
