"""empty message

Revision ID: 28095aae65f8
Revises: 1e9fbe3b7b63
Create Date: 2020-04-29 12:04:21.954629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28095aae65f8'
down_revision = '1e9fbe3b7b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.add_column('connection', sa.Column('ranking', sa.SmallInteger(), nullable=True))
    op.add_column('connection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'connection', 'organizers', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connection', type_='foreignkey')
    op.drop_column('connection', 'user_id')
    op.drop_column('connection', 'ranking')
    op.create_table('connections',
    sa.Column('organizer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('connection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name='connections_ibfk_1'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], name='connections_ibfk_2'),
    sa.PrimaryKeyConstraint('organizer_id', 'connection_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
