"""empty message

Revision ID: 43733a76cb70
Revises: 2cc74054be7c
Create Date: 2020-03-01 16:38:26.592910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43733a76cb70'
down_revision = '2cc74054be7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizers_password', table_name='organizers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_organizers_password', 'organizers', ['password'], unique=1)
    # ### end Alembic commands ###
