"""empty message

Revision ID: 9d2390b2dec4
Revises: 6370021418e2
Create Date: 2020-04-28 17:10:59.332051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d2390b2dec4'
down_revision = '6370021418e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.alter_column('participants', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('participants', 'organizer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'organizer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('participants', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_table('connections')
    # ### end Alembic commands ###
