"""empty message

Revision ID: af2bc5c7c0d6
Revises: 
Create Date: 2020-02-20 14:12:41.897914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2bc5c7c0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('organizerID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=True),
    sa.Column('lastContact', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('organizerID')
    )
    op.create_index(op.f('ix_assignments_lastContact'), 'assignments', ['lastContact'], unique=True)
    op.create_index(op.f('ix_assignments_medium'), 'assignments', ['medium'], unique=True)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=True)
    op.create_index(op.f('ix_assignments_studentID'), 'assignments', ['studentID'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstN', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lastN', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('organizationID', sa.Integer(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizers_email'), 'organizers', ['email'], unique=True)
    op.create_index(op.f('ix_organizers_firstN'), 'organizers', ['firstN'], unique=True)
    op.create_index(op.f('ix_organizers_lastN'), 'organizers', ['lastN'], unique=True)
    op.create_index(op.f('ix_organizers_organizationID'), 'organizers', ['organizationID'], unique=True)
    op.create_index(op.f('ix_organizers_password'), 'organizers', ['password'], unique=True)
    op.create_index(op.f('ix_organizers_username'), 'organizers', ['username'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstN', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lastN', sa.VARCHAR(length=255), nullable=True),
    sa.Column('targetID', sa.VARBINARY(length=255), nullable=True),
    sa.Column('organizationID', sa.Integer(), nullable=True),
    sa.Column('isOrganizer', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_firstN'), 'students', ['firstN'], unique=True)
    op.create_index(op.f('ix_students_isOrganizer'), 'students', ['isOrganizer'], unique=True)
    op.create_index(op.f('ix_students_lastN'), 'students', ['lastN'], unique=True)
    op.create_index(op.f('ix_students_organizationID'), 'students', ['organizationID'], unique=True)
    op.create_index(op.f('ix_students_targetID'), 'students', ['targetID'], unique=True)
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_students_targetID'), table_name='students')
    op.drop_index(op.f('ix_students_organizationID'), table_name='students')
    op.drop_index(op.f('ix_students_lastN'), table_name='students')
    op.drop_index(op.f('ix_students_isOrganizer'), table_name='students')
    op.drop_index(op.f('ix_students_firstN'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_organizers_username'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_password'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_organizationID'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_lastN'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_firstN'), table_name='organizers')
    op.drop_index(op.f('ix_organizers_email'), table_name='organizers')
    op.drop_table('organizers')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_assignments_studentID'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_medium'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_lastContact'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
