"""empty message

Revision ID: b7cfaeb81fb5
Revises: 20da05b98991
Create Date: 2020-04-28 18:39:51.120033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7cfaeb81fb5'
down_revision = '20da05b98991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('participants', 'organizer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'organizer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('participants', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
